# Libreto

# Creando repositorio y haciendo cosas básicas comparadas con RStudio

cd

mkdir my-first-repo

cd my-first-repo

# Comenzar control de versiones en un directorio

git init

# Un archivo al que se le haga control de cambios

echo "Welcome to My First Repo" > readme.txt

# Veamos el estado de la carpeta

git status

# Como se ve, el archivo recién creado no tiene seguimiento aún

git add readme.txt

# Git ahora sabe que ese archivo tiene seguimiento (staged)

git status

# Revisemos que entre comillas Git da algunos tips interesantes. Por ejemplo, como dejar de hacer controld e versiones a un archivo. Hagámoslo a ver qué pasa

git rm --cached readme.txt

git status

git add readme.txt

# Creación de un hito (commit)

git commit -m "added readme.txt"

# Revisemos el estado

git status


# Agreguemos más archivos

touch file1.txt

touch fil2.txt

ls

# Modifiquemos un archivo

echo "Learning Git is going well so far." >> readme.txt

git status

# Agreguemos todas las modificaciones

# Creemos un hito (commit)

git commit -m "added two files"

# Hay un error y debemos devolvernos a corregirlo:

git reset --soft HEAD~

git status

# Estamos exactamente en el punto exacto antes de crear el commit. Hagamos un cambio

mv fil2.txt file2.txt

git status

# Notemos el cambio de los archivos renombrados que el sistema asume como borrados y creemos control de versiones

git add -A

git status

# Hagamos el hito correctamente

git commit -m "added two files"
