# Pull Request

Un pull request le permite interactivamente comparar dos diferentes branches antes de concatenarlas con lo que usted puede seguir adelante o proporcionar cambios a quien abrió el pull request. Esencialmente un pull request le permite a una persona preguntarle a otra si está de acuerdo en incorporar cambios de un branch dentro de otro branch. Esta transacción social de código puede involucrarlo a usted y a un colaborador, a usted y a un extraño, o podría abrir un pull request en su propio repositorio como un método para mantenerse organizado.

# Crearemos un pull request propio

# Cambiémonos de branch

git checkout update-readme

ls

# Concatenemos

git merge master

# Hagamos cambios

rm *.txt
rm *.jpg
ls

# Abramos readme.txt con nano, borremos todo y peguemos esto:

# Sean Kross

### Geography

I live in the city of Baltimore, in the state of Maryland, in the United States
of America.

### Reading

Three of my favorite books are:

- *Mindstorms* by Seymour Papert
- *Welcome to the Monkey House* by Kurt Vonnegut
- *Persepolis* by Marjane Satrapi

### Food

Last night I dreamt about eating in these restaurants:

1. Linger in Denver.
2. Azura in Jerusalem.
3. Gemma in New York City.

### Contact

The best way to get in touch with me is [on Twitter](https://twitter.com/seankross).

# Creemos un hito

git add -A
git commit -m "made readme more personal"

# Subámoslo

git push origin update-readme

# Vayamos a GitHUb y ubiquémonos en el branch update

# Abramos un pull request

# Devolvámonos a master

git checkout master

git pull

